@server=http://localhost:3001

GET {{server}}/api/blogs HTTP/1.1

###

POST {{server}}/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "Testing",
    "author": "Alan Smithee",
    "url": "http://127.0.0.1",
    "likes": 42
}

###

DELETE {{server}}/api/blogs/5bba1581e59947d2a4c99e6d HTTP/1.1